FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Expose the port your app runs on
ENV port=8080
EXPOSE 8080
# Command to run your application
CMD ["python", "recs.py"]

#docker run -d -p 8080:8080 --name recommender recommender-app